---
apiVersion: v1
kind: Namespace
metadata:
  name: random-counter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-counter
  labels:
    name: random-counter
  namespace: random-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: random-counter
  template:
    metadata:
      labels:
        name: random-counter
    spec:
      containers:
        - name: random-log-counter
          image: zebrium/random-log-counter:latest
          imagePullPolicy: Always
---