apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: sock-chaos
  namespace: sock-shop
spec:
  engineState: 'active'
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments:
    - name: node-memory-hog
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '120'

            - name: MEMORY_CONSUMPTION_PERCENTAGE
              value: '50'
              