name: push-pipeline
on:
  push:
    branches:
      - master
      - v*
    tags:
      - "*"
jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        run: |
          cd litmus-portal
          make backend-services-checks

  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        run: |
          cd litmus-portal
          make frontend-services-checks

  get-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        run: |
          img_tag=""
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ ${array[1]} == "tags" ]
          then
              echo "tag build"
              img_tag=${GITHUB_REF#refs/*/}
          else
              echo "non tag build"
              img_tag="ci"
          fi
          # This is a condition where image tag looks like "pull/<pullrequest-name>" during pull request build
          NEW_IMG_TAG=`echo $img_tag | sed "s/\//-/g"`
          echo $NEW_IMG_TAG
          echo export IMG_TAG=$NEW_IMG_TAG >> env-vars
          echo export GRAPHQL_SERVER_IMAGE="litmusportal-server" >> env-vars
          echo export AUTHENTICATION_SERVER_IMAGE="litmusportal-auth-server" >> env-vars
          echo export FRONTEND_IMAGE="litmusportal-frontend" >> env-vars
          echo export SUBSCRIBER_IMAGE="litmusportal-subscriber" >> env-vars
          echo export EVENT_TRACKER="litmusportal-event-tracker" >> env-vars
      - name: Uploading envs
        uses: actions/upload-artifact@v2
        with:
          name: env_artifact
          path: env-vars

  docker-build-and-push-graphql-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
      - backend-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
      - name: Build graphql server docker image
        shell: bash
        run: |
          source env-vars
          cd litmus-portal/graphql-server
          docker build . -f build/Dockerfile -t ${{ secrets.REPONAME }}/${GRAPHQL_SERVER_IMAGE}:${IMG_TAG}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push graphql server docker image
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/*/}
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ $branch == "master" ] || [ ${array[1]} == "tags" ] || [[ $branch =~ ^v[0-9]*.[0-9]*.x$ ]]
          then
            source env-vars
            docker push ${{ secrets.REPONAME }}/${GRAPHQL_SERVER_IMAGE}:${IMG_TAG}
          fi

  docker-build-and-push-authentication-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
      - backend-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
      - name: Build auth server docker image
        shell: bash
        run: |
          source env-vars
          cd litmus-portal/authentication
          docker images && docker build . -f Dockerfile -t ${{ secrets.REPONAME }}/${AUTHENTICATION_SERVER_IMAGE}:${IMG_TAG}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push auth server docker image
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/*/}
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ $branch == "master" ] || [ ${array[1]} == "tags" ] || [[ $branch =~ ^v[0-9]*.[0-9]*.x$ ]]
          then
            source env-vars
            docker push ${{ secrets.REPONAME }}/${AUTHENTICATION_SERVER_IMAGE}:${IMG_TAG}
          fi

  docker-build-and-push-subscriber:
    runs-on: ubuntu-latest
    needs:
      - get-envs
      - backend-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
      - name: Build subscriber docker image
        shell: bash
        run: |
          source env-vars
          cd litmus-portal/cluster-agents/subscriber
          docker build . -f build/Dockerfile -t ${{ secrets.REPONAME }}/${SUBSCRIBER_IMAGE}:${IMG_TAG}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push subscriber docker image
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/*/}
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ $branch == "master" ] || [ ${array[1]} == "tags" ] || [[ $branch =~ ^v[0-9]*.[0-9]*.x$ ]]
          then
            source env-vars
            docker push ${{ secrets.REPONAME }}/${SUBSCRIBER_IMAGE}:${IMG_TAG}
          fi

  docker-build-and-push-event-tracker:
    runs-on: ubuntu-latest
    needs:
      - get-envs
      - backend-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
      - name: Build event tracker docker image
        shell: bash
        run: |
          source env-vars
          cd litmus-portal/cluster-agents/event-tracker
          docker build . -f Dockerfile -t ${{ secrets.REPONAME }}/${EVENT_TRACKER}:${IMG_TAG}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push event tracker docker image
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/*/}
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ $branch == "master" ] || [ ${array[1]} == "tags" ] || [[ $branch =~ ^v[0-9]*.[0-9]*.x$ ]]
          then
            source env-vars
            docker push ${{ secrets.REPONAME }}/${EVENT_TRACKER}:${IMG_TAG}
          fi

  docker-build-and-push-frontend:
    runs-on: ubuntu-latest
    needs:
      - get-envs
      - frontend-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
      - name: Build frontend docker image
        shell: bash
        run: |
          source env-vars
          cd litmus-portal/frontend
          timestamp=`date "+%s"`
          docker build . -f Dockerfile -t ${{ secrets.REPONAME }}/${FRONTEND_IMAGE}:${IMG_TAG} --build-arg REACT_APP_KB_CHAOS_VERSION=${IMG_TAG} --build-arg REACT_APP_BUILD_TIME="$timestamp" --build-arg REACT_APP_HUB_BRANCH_NAME="v1.13.x"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push frontend docker image
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/*/}
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ $branch == "master" ] || [ ${array[1]} == "tags" ] || [[ $branch =~ ^v[0-9]*.[0-9]*.x$ ]]
          then
            source env-vars
            docker push ${{ secrets.REPONAME }}/${FRONTEND_IMAGE}:${IMG_TAG}
          fi
